# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeseries.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10timeseries.proto\x12\ntimeseries\"N\n\rStreamRequest\x12\x17\n\x0fstart_timestamp\x18\x01 \x01(\x03\x12\x15\n\rend_timestamp\x18\x02 \x01(\x03\x12\r\n\x05limit\x18\x03 \x01(\x05\"\xd9\x05\n\x0eTimeSeriesData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x02\x12\x12\n\nEEG_CZ_REF\x18\x03 \x01(\x02\x12\x0f\n\x07\x45MG_REF\x18\x04 \x01(\x02\x12\x12\n\nEEG_28_REF\x18\x05 \x01(\x02\x12\x12\n\nEEG_30_REF\x18\x06 \x01(\x02\x12\x12\n\nEEG_P4_REF\x18\x07 \x01(\x02\x12\x12\n\nEEG_29_REF\x18\x08 \x01(\x02\x12\x13\n\x0b\x45\x45G_ROC_REF\x18\t \x01(\x02\x12\x12\n\nEEG_T2_REF\x18\n \x01(\x02\x12\x12\n\nEEG_T3_REF\x18\x0b \x01(\x02\x12\x12\n\nEEG_O1_REF\x18\x0c \x01(\x02\x12\r\n\x05SUPPR\x18\r \x01(\x02\x12\x12\n\nEEG_P3_REF\x18\x0e \x01(\x02\x12\x12\n\nEEG_FZ_REF\x18\x0f \x01(\x02\x12\x12\n\nEEG_F8_REF\x18\x10 \x01(\x02\x12\x12\n\nEEG_27_REF\x18\x11 \x01(\x02\x12\x12\n\nEEG_A1_REF\x18\x12 \x01(\x02\x12\x0b\n\x03IBI\x18\x13 \x01(\x02\x12\x0e\n\x06\x42URSTS\x18\x14 \x01(\x02\x12\x12\n\nEEG_F4_REF\x18\x15 \x01(\x02\x12\x14\n\x0c\x45\x45G_EKG1_REF\x18\x16 \x01(\x02\x12\x13\n\x0b\x45\x45G_LOC_REF\x18\x17 \x01(\x02\x12\x12\n\nEEG_T1_REF\x18\x18 \x01(\x02\x12\x12\n\nEEG_T4_REF\x18\x19 \x01(\x02\x12\x12\n\nEEG_C4_REF\x18\x1a \x01(\x02\x12\x12\n\nEEG_26_REF\x18\x1b \x01(\x02\x12\x12\n\nEEG_T5_REF\x18\x1c \x01(\x02\x12\x12\n\nEEG_A2_REF\x18\x1d \x01(\x02\x12\x13\n\x0b\x45\x45G_FP2_REF\x18\x1e \x01(\x02\x12\x13\n\x0b\x45\x45G_FP1_REF\x18\x1f \x01(\x02\x12\x12\n\nEEG_F3_REF\x18  \x01(\x02\x12\x12\n\nEEG_T6_REF\x18! \x01(\x02\x12\x12\n\nEEG_PZ_REF\x18\" \x01(\x02\x12\x12\n\nPHOTIC_REF\x18# \x01(\x02\x12\x12\n\nEEG_F7_REF\x18$ \x01(\x02\x12\x12\n\nEEG_O2_REF\x18% \x01(\x02\x32\x64\n\x11TimeSeriesService\x12O\n\x14StreamTimeSeriesData\x12\x19.timeseries.StreamRequest\x1a\x1a.timeseries.TimeSeriesData0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeseries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=32
  _globals['_STREAMREQUEST']._serialized_end=110
  _globals['_TIMESERIESDATA']._serialized_start=113
  _globals['_TIMESERIESDATA']._serialized_end=842
  _globals['_TIMESERIESSERVICE']._serialized_start=844
  _globals['_TIMESERIESSERVICE']._serialized_end=944
# @@protoc_insertion_point(module_scope)
